

# Forests
DENSITY_FOREST_TREE      = 0.10  # 10% chance
DENSITY_RAINFOREST_TREE  = 0.20  # 20% chance
DENSITY_RAINFOREST_MUSHROOM = 0.01

# Deserts
DENSITY_DESERT_CACTUS    = 0.02
DENSITY_DESERT_DEADBUSH  = 0.02
DENSITY_DESERT_ROCK      = 0.01

# Tropical
DENSITY_TROPICAL_PALM    = 0.05

# Cold / Mountains
DENSITY_TAIGA_SNOW_TREE  = 0.10
DENSITY_TAIGA_BERRY      = 0.10
DENSITY_TUNDRA_ROCK      = 0.04

# Grasslands
DENSITY_GRASSLAND_FLOWER = 0.005
